version: '3'
services:
  node:
    image: node:20-alpine
    user: node:node
    working_dir: /var/www/app
    volumes:
      - .:/var/www/app
    command: ['sh', '-c', 'npm ci && npx --yes concurrently "npm run start:storybook" "npm run start:dev"']
    ports:
      - 6009:6009
      - 5173:5173
      - 24678:24678
    tty: true
