name: PR Closed

on:
  pull_request:
    types: [closed]

jobs:
  pr-closed:
    - name: Setup aws
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Remove to S3
        run: aws s3 rm "s3://dev.blog.eleven-labs.com/${{ github.head_ref }}/" --recursive

    - name: Delete environment
      uses: bobheadxi/deployments@v1
      with:
        step: delete-env
        token: ${{ secrets.GITHUB_TOKEN }}
        env: "dev-${{ github.head_ref }}"
        desc: Environment was deleted
