name: PR Closed

on:
  pull_request_target:
    types: [closed]

jobs:
  pr-closed:
    runs-on: ubuntu-latest
    steps:
      - name: Install aws cli
        if: github.event_name == 'pull_request'
        id: install-aws-cli
        uses: unfor19/install-aws-cli-action@v1

      - name: Setup aws
        if: github.event_name == 'pull_request'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Remove to S3
        run: aws s3 rm "s3://${{ vars.AWS_BUCKET_NAME }}/${{ github.head_ref }}/" --recursive

      - name: Deactivate environment
        uses: bobheadxi/deployments@v1
        with:
          step: deactivate-env
          token: ${{ secrets.GITHUB_TOKEN }}
          env: "dev-${{ github.head_ref }}"
          desc: Environment was pruned
